name: build
on: [push]
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [sqlite3, mysql, postgres]
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: dbpassword
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: dbpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: ruby:2.7.3
      env:
        DB: ${{ matrix.db }}
        DB_USERNAME: root
        DB_PASSWORD: dbpassword
        DB_HOST: ${{ matrix.db }}
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: bash -x ./travis/travis_install.sh
      - name: Build
        run: bash -x ./travis/travis.sh
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: general
          SLACK_TITLE: Test Success
          SLACK_COLOR: good
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: general
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger

